#!/usr/bin/env node
/**
 * Writes js/config.js from environment variables.
 *
 * Env (either name works):
 *   SUPABASE_URL  or  VITE_SUPABASE_URL  or  NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_ANON_KEY  or  VITE_SUPABASE_ANON_KEY  or  NEXT_PUBLIC_SUPABASE_ANON_KEY
 *
 * Used by Vercel (Build Command: npm run build).
 * Local: copy .env.example → .env, fill values, run npm run build
 *        OR copy js/config.example.js → js/config.js
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const outFile = path.join(root, "js", "config.js");

function pick(...keys) {
  for (const k of keys) {
    const v = process.env[k];
    if (v && String(v).trim()) return String(v).trim();
  }
  return null;
}

// Optional: load .env if present (no dependency)
function loadDotEnv() {
  const envPath = path.join(root, ".env");
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, "utf8").split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (process.env[key] == null || process.env[key] === "") {
      process.env[key] = val;
    }
  }
}

loadDotEnv();

const supabaseUrl =
  pick(
    "SUPABASE_URL",
    "VITE_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_URL"
  ) || "https://YOUR_PROJECT_REF.supabase.co";

const supabaseAnonKey =
  pick(
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  ) || "YOUR_SUPABASE_ANON_KEY";

const isPlaceholder =
  supabaseUrl.includes("YOUR_PROJECT_REF") ||
  supabaseAnonKey.includes("YOUR_SUPABASE_ANON_KEY");

const content = `/* Auto-generated by scripts/build-config.js — do not commit secrets */
/* Source: env SUPABASE_URL + SUPABASE_ANON_KEY (or placeholders) */
window.CAWNPORE_CONFIG = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, "utf8");

if (isPlaceholder) {
  console.log(
    "[build-config] Wrote js/config.js with PLACEHOLDERS (local SQLite / not configured yet)."
  );
  console.log(
    "[build-config] Set SUPABASE_URL and SUPABASE_ANON_KEY for production."
  );
} else {
  const host = supabaseUrl.replace(/^https?:\/\//, "").split("/")[0];
  console.log(`[build-config] Wrote js/config.js for ${host}`);
}
